#!/bin/bash

sudo rm ~/.zshrc
sudo ln -s ~/dotfiles/zshrc ~/.zshrc
sudo rm -r ~/.zsh
sudo ln -s ~/dotfiles/zsh ~/.zsh
mkdir ~/.zsh/run

sudo rm ~/.vimrc
sudo ln -s ~/dotfiles/vimrc ~/.vimrc
sudo rm -r ~/.vim
sudo ln -s ~/dotfiles/zsh ~/.vim
