alias ls='ls --color=auto'
alias Y='yaourt'
alias yaup='yaourt -Syu'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias startsshd='sudo systemctl start sshd'
alias ll='ls -lFh'
alias la='ls -lAFh'
alias grep='grep --color'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
